"""
This type stub file was generated by pyright.
"""

def get_docs_view(title=..., description=..., schema_url=..., urlconf=..., public=..., patterns=..., generator_class=..., authentication_classes=..., permission_classes=..., renderer_classes=...): # -> Callable[..., HttpResponse]:
    ...

def get_schemajs_view(title=..., description=..., schema_url=..., urlconf=..., public=..., patterns=..., generator_class=..., authentication_classes=..., permission_classes=...): # -> Callable[..., HttpResponse]:
    ...

def include_docs_urls(title=..., description=..., schema_url=..., urlconf=..., public=..., patterns=..., generator_class=..., authentication_classes=..., permission_classes=..., renderer_classes=...): # -> tuple[list[URLResolver], str | None, str | None]:
    ...

