# Generated by Django 5.0.6 on 2024-06-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('max_current', models.IntegerField()),
                ('avg_current', models.IntegerField()),
            ],
        ),
    ]
